name: da_infographic

on:
  schedule:
    - cron: '0 */6 * * *'  # Setiap 6 jam

jobs:
  publish-data:
    runs-on: macos-latest
    env:
      ELEPHANT_SQL_DBNAME: ${{ secrets.ELEPHANT_SQL_DBNAME }}
      ELEPHANT_SQL_HOST: ${{ secrets.ELEPHANT_SQL_HOST }}
      ELEPHANT_SQL_USER: ${{ secrets.ELEPHANT_SQL_USER }}
      ELEPHANT_SQL_PASSWORD: ${{ secrets.ELEPHANT_SQL_PASSWORD }}
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Instal paket rvest
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)'
      - name: Instal paket rtweet
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Instal paket PostgreSQL
        run: Rscript -e 'install.packages("RPostgreSQL", dependencies = TRUE)'
      - name: Eksekusi Script da_infographic.R
        run: Rscript save.R
     # Add new files in data folder, commit along with other modified files, push
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push