name: Save

on:
  schedule:
    - cron: '0 2 * * *'  # Setiap hari jam 9 pagi

jobs:
  save-data:
    runs-on: macOS-latest
    env:
      ELEPHANT_SQL_DBNAME: ${{ secrets.ELEPHANT_SQL_DBNAME }}
      ELEPHANT_SQL_HOST: ${{ secrets.ELEPHANT_SQL_HOST }}
      ELEPHANT_SQL_USER: ${{ secrets.ELEPHANT_SQL_USER }}
      ELEPHANT_SQL_PASSWORD: ${{ secrets.ELEPHANT_SQL_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Instal paket rvest
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)'
      - name: Instal paket rtweet
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install paket RPostgreSQL
        run: Rscript -e 'install.packages("RPostgreSQL", dependencies = TRUE)'
      - name: Instal paket urlshorteneR
        run: Rscript -e 'install.packages("urlshorteneR", dependencies = TRUE)'
      - name: Run The R Script
        run: Rscript save.R